#This is a Build Deploy Pipeline for .NET 6 Web App to Azure App Service using Azure DevOps Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

  
stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:  
steps:
        - task: UseDotNet@2
          inputs:
            version: $(dotNetVersion)
            includePreviewVersions: true
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'Build .NET 6 Application'
       
        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)' 
            artifactName: 'MinimalAPI'


# Publish it as .NET 6 self-contained application for linux runtime
#- task: DotNetCoreCLI@2
  #inputs:
    #command: publish
    #publishWebProjects: False
    #arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --runtime $(targetRuntime) --output $(Build.ArtifactStagingDirectory)'
    #zipAfterPublish: True

# Package the file and uploads them as an artifact of the build
